BelasitsaSkyRun.Umbraco/Models/ContactUsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BelasitsaSkyRun.Umbraco.Models
{
    public class ContactUsModel
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { set; get; }  
            
        [Required(ErrorMessage = "Please enter a valid email address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        public string Email { set; get; }

        [Required(ErrorMessage = "Please write your message")]
        public string Message { get; set; }

    }
}

BelasitsaSkyRun.Umbraco/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BelasitsaSkyRun.Umbraco.Models
{
    public class LoginModel
    {
        [Display(Name = "UserName")]
        [Required]
        public string UserName { get; set; }

        [Display(Name = "Email")]
        [Required]     
        public string Email { get; set; }

        [Display(Name = "BirthPlace")]
        [Required]      
        public string BirthPlace { get; set; }

        [Display(Name = "BirthDate")]
        [Required]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Gender")]
        [Required]
        public bool Gender { get; set; }
    }
}

BelasitsaSkyRun.Umbraco/Controllers/ContactFormController.cs
using BelasitsaSkyRun.Umbraco.Models;
using System;
using System.Net.Mail;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace BelasitsaSkyRun.Umbraco.Controllers
{
    public class ContactFormController : SurfaceController
    {
        [HttpGet]
        public ActionResult ContactUsTemplate()
        {
            ContactUsModel model = new ContactUsModel();

            return View("~/Views/Shared/ContactUsForm.cshtml", model);
        }

        [HttpPost]
        public ActionResult ContactUsTemplate(ContactUsModel model)
        {
            if (ModelState.IsValid)
            {
                string subject = string.Format("{0} - {1}", model.Email, model.Name);

                string body = string.Format("<b>Email: </b>{2}<br/><b>Name: </b>{1}<br/><b>Message: </b> <br/><br/> {0}",
                    model.Message.Replace("\r", "").Replace("\n", "<br />"),
                    model.Name,
                    model.Email);

                SendEmail(model.Email, model.Name, subject, body);

                Response.Redirect("/mk/thankyoupage/");
            }
            return View("~/Views/Shared/ContactUsForm.cshtml", model);
        }





        public string SendEmail(string email, string displayName, string subject, string body)
        {
            if (!string.IsNullOrEmpty(body) &&
                !string.IsNullOrEmpty(email) &&
                !string.IsNullOrEmpty(displayName) &&
                !string.IsNullOrEmpty(subject))
            {
                using (SmtpClient smtp = new SmtpClient())
                {
                    MailAddress to = new MailAddress("lyubomir.shumantov@klevret.com");
                    MailAddress from = new MailAddress(email, displayName);
                    MailMessage message = new MailMessage(from, to);
                    message.Subject = subject;      //"Using the new SMTP client.";
                    message.Body = body;            // @"Using this new feature, you can send an e-mail message from an application very easily.";
                    message.IsBodyHtml = true;
                    SmtpClient client = new System.Net.Mail.SmtpClient();

                    try
                    {
                        client.Send(message);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Exception caught in CreateTestMessage2(): {0}",
                                    ex.ToString());
                    }

                }
                return "TODO: Return Url";

            }
            return null;
        }
    }
}

BelasitsaSkyRun.Umbraco/Controllers/MemberController.cs
using BelasitsaSkyRun.Umbraco.Models;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Core.Services;
using Umbraco.Web.Mvc;
using Umbraco.Core.Events;
using Umbraco.Core.Models;
using Umbraco.Core;
using umbraco.NodeFactory;
using System;
using Umbraco.Web;

namespace BelasitsaSkyRun.Umbraco.Controllers
{
    public class MemberController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginModel());
        }
        public ActionResult SubmitLogin([Bind(Include = "UserName,Email,BirthPlace,BirthDate,Gender")] LoginModel model)
        {


            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            var memberService = Services.MemberService;
            if (memberService.GetByEmail(model.Email) != null)
            {
                ModelState.AddModelError("", "Member already exists");
                return CurrentUmbracoPage();
            }
            var member = memberService.CreateMemberWithIdentity(model.UserName, model.Email, model.BirthPlace, "Member");
            member.SetValue("UserName", model.UserName);
            member.SetValue("Email", model.Email);
            member.SetValue("BirthPlace", model.BirthPlace);
            member.SetValue("BirthDate", model.BirthDate);
            member.SetValue("Gender", model.Gender);



            MemberService.Saving += MemberServiceOnSaving;

            memberService.Save(member);
            //MemberType demoMemberType = new MemberType(1044); //id of membertype ‘demo’
            //Member newMember = Member.MakeNew(model.BirthDate + " " + model.BirthPlace + " " + model.Email + " " + model.Gender + " " + model.UserName , demoMemberType, new umbraco.BusinessLogic.User(0));
            //newMember.Email = "test@testmail.com";
            //newMember.Password = "password";
            //newMember.LoginName = "Test";
            //newMember.getProperty("firstName").Value = "test";
            //newMember.Save();     
            // memberService.SavePassword(member, model.Password);

            Members.Login(model.Email, model.Email);



            return Redirect("/");
        }





        private void MemberServiceOnSaving(IMemberService sender, SaveEventArgs<IMember> e)
        {
            foreach (var member in e.SavedEntities)
            {
                bool IsApprovedBug = member.IsApproved; //BUG: Always return true

                var m = ApplicationContext.Current.Services.MemberService.GetById(member.Id);
                //m.AdditionalData.Add.e();
                //var IsApproved = m.IsApproved; //Correct value


            }
        }


        public ActionResult RenderLogout()
        {
            return PartialView("_Logout", null);
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }

    }
}

BelasitsaSkyRun.Umbraco/Views/Accomodation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
    var lang_cur = System.Threading.Thread.CurrentThread.CurrentUICulture.IetfLanguageTag.ToLower().Substring(0, 2);

}

<div id="middle">
    @{Html.RenderPartial("Bredcamp");}
    <div class="middle_inner">
        <div class="content_wrap r_sidebar">
            <div class="content entry" style="width:100%;">
                <div class="blog opened-article">
                    <article class="post format-standard hentry">
                        <header class="cmsms_post_header entry-header">
                            <span class="cmsms_post_format_img cmsms-icon-home"></span>
                            <h1 class="cmsms_post_title entry-title" style="margin-top: -42px;">@CurrentPage.GetPropertyValue("title_" + lang_cur)</h1>
                        </header>
                        <p>@CurrentPage.GetPropertyValue("description_" + lang_cur)</p>
                        <div class="cmsms_post_content entry-content">
                            <div id="cmsms_row_554b576c54360" class="cmsms_row cmsms_color_scheme_default">
                                <div class="cmsms_row_outer_parent">
                                    <div class="cmsms_row_outer">
                                        <div class="cmsms_row_inner">
                                            <div class="cmsms_row_margin">
                                                <div class="cmsms_column one_first">
                                                    <div id="cmsms_row_555469b2e68c8" class="cmsms_row cmsms_color_scheme_default">
                                                        <div class="cmsms_row_outer_parent">
                                                            <div class="cmsms_row_outer">
                                                                <div class="cmsms_row_inner">
                                                                    <div class="cmsms_row_margin">
                                                                        <div class="cmsms_column one_first">
                                                                            <div class="cmsms_tabs tabs_mode_tour tabs_pos_left">
                                                                                <ul class="cmsms_tabs_list">
                                                                                    <li id="cmsms_tabs_list_item_555469b2e6dd4" class="cmsms_tabs_list_item current_tab">

                                                                                        <a href="#">
                                                                                            <span>Short Info</span>

                                                                                            @{
                                                                                                var end = CurrentPage.GetPropertyValue("category");

                                                                                                for (int i = 0; i < end; i++)
                                                                                                {
                                                                                                    <i class="fa fa-star" aria-hidden="true" style="float:right; padding-left: 3px;"></i>
                                                                                                }
                                                                                            }

                                                                                        </a>

                                                                                    </li>
                                                                                    <li id="cmsms_tabs_list_item_555469b2e6f0f" class="cmsms_tabs_list_item">
                                                                                        <a href="#"><span>Contacts</span></a>
                                                                                    </li>
                                                                                    <li id="cmsms_tabs_list_item_555469b2e704e" class="cmsms_tabs_list_item">
                                                                                        <a href="#"><span>Capacity</span></a>
                                                                                    </li>
                                                                                    <li id="cmsms_tabs_list_item_555469b2e7185" class="cmsms_tabs_list_item">
                                                                                        <a href="#"><span>Gallery</span></a>
                                                                                    </li>
                                                                                </ul>
                                                                                <div class="cmsms_tabs_wrap">
                                                                                    <div id="cmsms_tab_555469b2e6dd4" class="cmsms_tab active_tab">
                                                                                        <div class="cmsms_tab_inner">
                                                                                            <h2>Short Info</h2>
                                                                                            <p>@CurrentPage.GetPropertyValue("shortDescription_" + lang_cur)</p>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div id="cmsms_tab_555469b2e6f0f" class="cmsms_tab">
                                                                                        <div class="cmsms_tab_inner">
                                                                                            <h2>Contacts</h2>
                                                                                            <p>@CurrentPage.GetPropertyValue("contact_" + lang_cur)</p>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div id="cmsms_tab_555469b2e704e" class="cmsms_tab">
                                                                                        <div class="cmsms_tab_inner">
                                                                                            <h2>Capacity</h2>
                                                                                            <p>@CurrentPage.GetPropertyValue("capacity_" + lang_cur)</p>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div id="cmsms_tab_555469b2e7185" class="cmsms_tab">
                                                                                        <div class="cmsms_tab_inner">
                                                                                            <h2>Gallery</h2>
                                                                                            @if (Model.Content.HasValue("gallery_" + lang_cur))
                                                                                            {
                                                                                                var caseStudyImagesList = Model.Content.GetPropertyValue<string>("gallery_" + lang_cur).Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
                                                                                                var caseStudyImagesCollection = Umbraco.TypedMedia(caseStudyImagesList).Where(x => x != null);

                                                                                                foreach (var caseStudyImage in caseStudyImagesCollection)
                                                                                                {
                                                                                                    <a href="@caseStudyImage.Url" rel="ilightbox"><img src="@caseStudyImage.Url" style="width:200px;height:200px" class="alignnone size-thumbnail" alt="6772398921_e349a76c6c_b1" width="200" height="200" /></a>

                                                                                                }
                                                                                            }
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cmsms_text" style="margin-top: 40px;">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="cl"></div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</div>

BelasitsaSkyRun.Umbraco/Views/Articles.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
    var lang_cur = System.Threading.Thread.CurrentThread.CurrentUICulture.IetfLanguageTag.ToLower().Substring(0, 2);

}
<style>
    .imgdisc {
        position: relative;
        background: rgb(158, 213, 91);
        padding: 15px;
        color: #ffffff;
    }
</style>

<div id="page" class="csstransition cmsms_liquid fixed_header hfeed site">
    <div id="main">
        <div id="middle">
            @{Html.RenderPartial("Bredcamp");}
            <div class="middle_inner">
                <div class="content_wrap r_sidebar">
                    <div class="content entry" @*role="main"*@>
                        <div class="blog opened-article">
                            <article class="post format-standard hentry">
                                <header class="cmsms_post_header entry-header">
                                    <span class="cmsms_post_format_img cmsms-icon-home"></span>
                                    <h1 class="cmsms_post_title entry-title" style="margin-top: -44px">@CurrentPage.GetPropertyValue("title_" + lang_cur)</h1>
                                </header>
                                <div style="font-size:16px">

                                    <p>@CurrentPage.GetPropertyValue("shortDescription_" + lang_cur)</p>

                                </div>
                                <div class="cmsms_post_content entry-content">
                                    <div id="cmsms_row_554b576c54360" class="cmsms_row cmsms_color_scheme_default">
                                        <div class="cmsms_row_outer_parent">
                                            <div class="cmsms_row_outer">
                                                <div class="cmsms_row_inner">
                                                    <div class="cmsms_row_margin">
                                                        <div class="cmsms_column one_first">
                                                            @if (Model.Content.HasValue("image"))
                                                            {
                                                                <figure>
                                                                    <img src='@CurrentPage.GetCropUrl("image", "articlesTop")' alt="Bear Population" title="Bear Population" class="<full-width></full-width>">
                                                                    <div>
                                                                        <p class="imgdisc">@CurrentPage.GetPropertyValue("imageName_" + lang_cur)</p>
                                                                    </div>
                                                                </figure>
                                                            }
                                                            else
                                                            {
                                                                <span class="cmsms_post_format_img cmsms-icon-picture"></span>
                                                            }

                                                            <div class="text" style="font-size:15px;margin-top: 40px;">
                                                                <p>@CurrentPage.GetPropertyValue("description_" + lang_cur)</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @if (Model.Content.HasValue("mediaPicker") == true)
        {
            <div id="main">
                <div id="cmsms_row_555343bed7ad3" class="cmsms_row cmsms_color_scheme_default" data-stellar-background-ratio="0.5">
                    <div class="cmsms_row_outer_parent">
                        <div class="cmsms_row_outer">
                            <div class="cmsms_row_inner">
                                <div class="cmsms_row_margin">
                                    <div class="cmsms_row_inner">
                                        <div class="cmsms_row_margin">
                                            <div class="cmsms_row_margin cmsms_14141414">
                                                @if (Model.Content.HasValue("mediaPicker"))
                                                {
                                                    var caseStudyImagesList = Model.Content.GetPropertyValue<string>("mediaPicker").Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
                                                    var caseStudyImagesCollection = Umbraco.TypedMedia(caseStudyImagesList).Where(x => x != null);


                                                    foreach (var caseStudyImage in caseStudyImagesCollection)
                                                    {
                                                        <div class="cmsms_column one_fourth">
                                                            <div class="cmsms_img  cmsms_image_n with_caption">
                                                                <a href="@caseStudyImage.Url" rel="ilightbox">
                                                                    <img src="@caseStudyImage.Url" style="height:212px;" />
                                                                </a>
                                                                <p class="cmsms_img_caption"></p>
                                                            </div>
                                                        </div>
                                                    }
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BelasitsaSkyRun.Umbraco/Views/BaseCore.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BaseCore>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

BelasitsaSkyRun.Umbraco/Views/BasePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BasePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

BelasitsaSkyRun.Umbraco/Views/ContactForm/Index.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

BelasitsaSkyRun.Umbraco/Views/ContactUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
    var lang_cur = System.Threading.Thread.CurrentThread.CurrentUICulture.IetfLanguageTag.ToLower().Substring(0, 2);

}



<div id="page" class="csstransition cmsms_liquid fixed_header hfeed site">
    <div id="main">
        <section id="middle">
            @{Html.RenderPartial("Bredcamp");}
            <div class="headline cmsms_color_scheme_default">
                <div class="fixContact" style="height:110px;margin-top: 20px;">
                    <div class="headline_color"></div>
                    <div class="headline_inner align_left">
                        <div class="headline_aligner"></div><div class="headline_text"><h1 class="entry-title">@CurrentPage.GetPropertyValue("title_" + lang_cur)</h1></div>
                    </div>
                </div>
            </div>
            <div class="middle_inner">


                <div id="map" style="height: 600px; width: 100%; pointer-events:none;"></div>
                <script>
                    function initMap() {
                        var uluru = { lat: 41.4378004, lng: 22.6427428 };
                        var map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 12,
                            center: uluru
                        });
                        var marker = new google.maps.Marker({
                            position: uluru,
                            map: map
                        });
                    }
                </script>
                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTu281AkaJ7C3uAeyZIheNF3JsB6-wJug&callback=initMap">

                </script>

                <div id="cmsms_row_555091c556fa4" class="cmsms_row cmsms_color_scheme_default">
                    <div class="cmsms_row_outer_parent">
                        <div class="cmsms_row_outer">
                            <div class="cmsms_row_inner">
                                <div class="cmsms_row_margin">
                                    <div class="cmsms_column one_half">
                                        <h3 id="cmsms_heading_555091c557200" class="cmsms_heading">@Umbraco.GetDictionaryValue("ContactSendMessageHeader")</h3>
                                        <div class="cmsms_contact_form">
                                            <div class="cmsms-form-builder">
                                                <div class="cmsms_notice cmsms_notice_success cmsms-icon-check-2 success_box widgetinfo" style="display:none;">
                                                    <div class="notice_icon"></div>
                                                    <div class="notice_content">
                                                        <p>Thank You! <br />Your message has been sent successfully.</p>
                                                    </div>
                                                </div>

                                                @Html.Action("ContactUsTemplate", "ContactForm")


                                            </div>
                                        </div>
                                    </div>
                                    <div class="cmsms_column one_half">
                                        <h3 id="cmsms_heading_555091c5584b3" class="cmsms_heading">@Umbraco.GetDictionaryValue("ContactInfoTitle")<br /></h3>
                                        <div class="cmsms_text" style="margin-top: 40px;white-space: pre-line;font-size:15px;">
                                            <p>@CurrentPage.GetPropertyValue("description_" + lang_cur)</p>
                                            <p>&nbsp;</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cl"></div>
            </div>
        </section>
        <a href="javascript:void(0);" id="slide_top" class="cmsms-icon-up-open-mini"></a>
    </div>
</div>

BelasitsaSkyRun.Umbraco/Views/ContainerGeneral.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContainerGeneral>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

BelasitsaSkyRun.Umbraco/Views/FileUpload.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FileUpload>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

BelasitsaSkyRun.Umbraco/Views/ImageBaner.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ImageBaner>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

BelasitsaSkyRun.Umbraco/Views/Member/Index.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

BelasitsaSkyRun.Umbraco/Views/Partials/Bredcamp.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{

    var lang_cur = System.Threading.Thread.CurrentThread.CurrentUICulture.IetfLanguageTag.ToLower().Substring(0, 2);

}
<div class="cmsms_breadcrumbs">
    <div class="cmsms_breadcrumbs_inner align_right">

        <ul class="breadcrumb">
            @foreach (var page in CurrentPage.Ancestors().OrderBy("Level"))
            {
                if (page.DocumentTypeAlias == "containerArticles")
                {
                    <li class="cms_home"><a href="#">@page.GetPropertyValue("title_" + lang_cur)</a></li>
                            <span class="breadcrumbs_sep"> / </span>
                }
                else
                {
                    <li class="cms_home"><a href="@page.Url">@page.GetPropertyValue("title_" + lang_cur)</a></li>
                            <span class="breadcrumbs_sep"> / </span>
                }
            }

            <li class="active">@CurrentPage.GetPropertyValue("title_" + lang_cur)</li>
        </ul>

    </div>
</div>

BelasitsaSkyRun.Umbraco/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}